on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '[RELEASE]')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install GTK4
        run: sudo apt-get install -y libgtk-4-dev libadwaita-1-dev libgirepository1.0-dev

      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Extract release version
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/^\[RELEASE\] *//p')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build x64
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o tconv-${{ steps.vars.outputs.SHORT_SHA }}-x64 .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tconv-binaries
          path: tconv-*
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: tconv-binaries

      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Extract release version
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/^\[RELEASE\] *//p')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create git tag
        run: git tag -f ${{ steps.vars.outputs.VERSION }}

      - name: Push tag
        run: git push -f origin ${{ steps.vars.outputs.VERSION }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.VERSION }}
          name: Release ${{ steps.vars.outputs.VERSION }}
          files: tconv-${{ steps.vars.outputs.SHORT_SHA }}-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
